export const ROUTE_PATH = {
  auth: 'auth',
  withHeader: 'with-header',
  withSideBar: 'with-side-bar',
  home: 'home',
  taskEditPage: 'task-edit-page',
  tasksPage: 'tasks-page',
  noteEditPage: 'note-edit-page',
  notesPage: 'notes-page',
  spaceEditPage: 'space-edit-page',
  spacesPage: 'spaces-page',
  userEditPage: 'user-edit-page',
  incomesPage: 'incomes-page',
  incomeEditPage: 'income-edit-page',
  expensesPage: 'expenses-page',
  expenseEditPage: 'expense-edit-page',
  balancePage: 'balance-page',
};
